# Generated by Django 2.0.5 on 2020-05-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='image',
            field=models.ImageField(null=True, upload_to='Plot/%Y/%m/%d/'),
        ),
    ]
