# Generated by Django 2.0.5 on 2020-05-31 14:51

import Plots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plots', '0004_auto_20200531_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='image',
            field=models.ImageField(null=True, upload_to=Plots.models.get_upload_path),
        ),
    ]
