# Generated by Django 2.0.5 on 2020-07-18 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Plots', '0005_auto_20200531_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plot',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='plot',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='plot',
            name='function',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
