# Generated by Django 2.0.5 on 2020-07-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plots', '0006_auto_20200718_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='function',
            field=models.TextField(default='r'),
        ),
    ]
