# Generated by Django 2.0.5 on 2020-07-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plots', '0007_auto_20200718_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='function',
            field=models.TextField(),
        ),
    ]
