# Generated by Django 2.0.5 on 2020-07-19 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Plots', '0008_auto_20200718_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='interval',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plot',
            name='step',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
