# Generated by Django 2.0.5 on 2020-05-31 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muser',
            name='user',
        ),
        migrations.DeleteModel(
            name='MUser',
        ),
    ]
